---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.01"
            memory: "10Mi"
          limits:
            memory: "200Mi"
            cpu: "0.01"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service  
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  type: NodePort
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: test-name-
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:  
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "for i in 11 10 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
